FROM nvidia/cuda:12.8.0-cudnn-runtime-ubuntu22.04 
COPY --from=ghcr.io/astral-sh/uv:0.5.25 /uv /uvx /bin/

RUN /bin/uv python install 3.12

ADD . /app

WORKDIR /app
RUN /bin/uv sync --extra cude --frozen --compile-bytecode
