FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.5.25 /uv /uvx /bin/

COPY pyproject.toml uv.lock /app/ 
WORKDIR /app
RUN /bin/uv sync --extra cpu --frozen --compile-bytecode --no-install-project

COPY ./src README.md /app/
RUN /bin/uv sync --extra cpu --frozen --compile-bytecode

ENTRYPOINT [ "/bin/uv", "run", "--no-sync" ]
