FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.5.25 /uv /uvx /bin/

ADD . /app

WORKDIR /app
RUN /bin/uv sync --extra cpu --frozen --compile-bytecode

ENTRYPOINT [ "/bin/uv", "run", "--no-sync" ]
